# Generated by Django 5.2.6 on 2025-10-20 22:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voice_commands/')),
                ('transcribed_text', models.TextField(blank=True, help_text='Texto transcrito del audio', null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Procesando'), ('TRANSCRIBED', 'Transcrito'), ('EXECUTED', 'Ejecutado'), ('FAILED', 'Fallido')], default='PROCESSING', max_length=20)),
                ('command_type', models.CharField(blank=True, help_text='Tipo de comando: reporte, consulta, etc.', max_length=50, null=True)),
                ('interpreted_params', models.JSONField(blank=True, default=dict, help_text='Parámetros extraídos del comando')),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Datos del reporte generado')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Duración del audio en segundos', null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Tiempo de procesamiento en milisegundos', null=True)),
                ('confidence', models.FloatField(blank=True, help_text='Confianza de la transcripción (0-1)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comando de Voz',
                'verbose_name_plural': 'Comandos de Voz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceCommandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(help_text='Etapa del procesamiento', max_length=50)),
                ('message', models.TextField(help_text='Mensaje descriptivo')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('voice_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='voice_commands.voicecommand')),
            ],
            options={
                'verbose_name': 'Historial de Comando',
                'verbose_name_plural': 'Historial de Comandos',
                'ordering': ['timestamp'],
            },
        ),
    ]
