# Generated by Django 5.2.7 on 2025-10-21 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_commands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voicecommand',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comando de Texto', 'verbose_name_plural': 'Comandos de Texto'},
        ),
        migrations.RemoveField(
            model_name='voicecommand',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='voicecommand',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='voicecommand',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='voicecommand',
            name='transcribed_text',
        ),
        migrations.AddField(
            model_name='voicecommand',
            name='command_text',
            field=models.TextField(default='comando sin texto', help_text='Texto del comando ingresado por el usuario'),
        ),
        migrations.AddField(
            model_name='voicecommand',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='Confianza en la interpretación del comando (0-1)', null=True),
        ),
        migrations.AlterField(
            model_name='voicecommand',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Procesando'), ('EXECUTED', 'Ejecutado'), ('FAILED', 'Fallido')], default='PROCESSING', max_length=20),
        ),
        migrations.AlterField(
            model_name='voicecommand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_commands', to=settings.AUTH_USER_MODEL),
        ),
    ]
