# Generated by Django 5.2.6 on 2025-10-20 21:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='FCM device token', max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], default='WEB', max_length=20)),
                ('device_name', models.CharField(blank=True, help_text='Nombre del dispositivo', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Token activo/válido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Dispositivo',
                'verbose_name_plural': 'Tokens de Dispositivos',
                'ordering': ['-last_used'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Notificaciones habilitadas')),
                ('sale_notifications', models.BooleanField(default=True, help_text='Notificaciones de ventas')),
                ('product_notifications', models.BooleanField(default=True, help_text='Notificaciones de productos')),
                ('report_notifications', models.BooleanField(default=True, help_text='Notificaciones de reportes')),
                ('ml_notifications', models.BooleanField(default=True, help_text='Notificaciones de ML')),
                ('system_notifications', models.BooleanField(default=True, help_text='Notificaciones del sistema')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Inicio de horario silencioso', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Fin de horario silencioso', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SALE_CREATED', 'Venta Creada'), ('SALE_UPDATED', 'Venta Actualizada'), ('SALE_DELETED', 'Venta Eliminada'), ('PRODUCT_LOW_STOCK', 'Stock Bajo'), ('PRODUCT_CREATED', 'Producto Creado'), ('REPORT_GENERATED', 'Reporte Generado'), ('ML_PREDICTION', 'Predicción ML'), ('SYSTEM', 'Sistema'), ('CUSTOM', 'Personalizado')], default='CUSTOM', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, help_text='Datos adicionales en formato JSON', null=True)),
                ('fcm_message_id', models.CharField(blank=True, help_text='ID del mensaje FCM', max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('FAILED', 'Fallido'), ('READ', 'Leído')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['status', '-created_at'], name='notificatio_status_37b3f3_idx')],
            },
        ),
    ]
