# Generated by Django 5.2.6 on 2025-10-21 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuarios',
                'db_table': 'user_sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='Username guardado por redundancia (en caso de eliminación del usuario)', max_length=150)),
                ('action_type', models.CharField(choices=[('AUTH', 'Autenticación'), ('CREATE', 'Creación'), ('READ', 'Lectura'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('REPORT', 'Generación de Reporte'), ('PAYMENT', 'Pago/Transacción'), ('CONFIG', 'Configuración'), ('ML', 'Acción de Machine Learning'), ('OTHER', 'Otra')], db_index=True, default='OTHER', help_text='Tipo de acción realizada', max_length=20)),
                ('action_description', models.TextField(help_text='Descripción detallada de la acción')),
                ('http_method', models.CharField(db_index=True, help_text='Método HTTP (GET, POST, PUT, DELETE, etc.)', max_length=10)),
                ('endpoint', models.CharField(db_index=True, help_text='URL del endpoint accedido', max_length=500)),
                ('query_params', models.TextField(blank=True, help_text='Parámetros de la URL (query string)')),
                ('request_body', models.TextField(blank=True, help_text='Cuerpo de la petición (para POST/PUT)')),
                ('response_status', models.IntegerField(db_index=True, help_text='Código de estado HTTP de la respuesta')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Tiempo de respuesta en milisegundos', null=True)),
                ('success', models.BooleanField(db_index=True, default=True, help_text='Si la operación fue exitosa')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si la operación falló')),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='Dirección IP del usuario')),
                ('user_agent', models.TextField(blank=True, help_text='User Agent del navegador/aplicación')),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], db_index=True, default='LOW', help_text='Nivel de severidad de la acción', max_length=10)),
                ('additional_data', models.JSONField(blank=True, help_text='Datos adicionales en formato JSON', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Fecha y hora exacta de la acción')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción (null si es anónimo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'user'], name='audit_logs_timesta_d733ec_idx'), models.Index(fields=['action_type', '-timestamp'], name='audit_logs_action__952b82_idx'), models.Index(fields=['ip_address', '-timestamp'], name='audit_logs_ip_addr_345630_idx'), models.Index(fields=['success', '-timestamp'], name='audit_logs_success_4e6301_idx')],
            },
        ),
    ]
