# Generated by Django 5.1.4 on 2025-10-28 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Garantía Estándar 1 Año', max_length=100, unique=True)),
                ('duration_days', models.PositiveIntegerField(default=365, help_text='Duración de la garantía en días')),
                ('details', models.TextField(blank=True, help_text='Detalles sobre qué cubre la garantía', null=True)),
            ],
            options={
                'verbose_name': 'Garantía',
                'verbose_name_plural': 'Garantías',
                'ordering': ['duration_days'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.warranty'),
        ),
    ]
